services:
  trainer:
    build: .
    image: zulu-classifier:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - "./base_model:/app/base_model"
      - "./datasets:/app/datasets:ro"
      - "./finetuned_model:/app/finetuned_model"
    command: python3 scripts/finetune.py
